package eu.clarin.cmdi.virtualcollectionregistry.core.pid;

import com.fasterxml.jackson.core.JsonProcessingException;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.UnsupportedEncodingException;

public class DoiPersistentIdentifierProviderTest {//extends WicketTesterEnabledTest {
    private static final Logger logger = LoggerFactory.getLogger(DoiPersistentIdentifierProvider.class);

    private static String prefix = "10.5438";

    //private PermaLinkService permaLinkService = new PermaLinkServiceImpl(TestApplication.BASE_URI);

    @Test
    public void testCreate() throws JsonProcessingException, UnsupportedEncodingException {
/*
        VirtualCollection vc = new VirtualCollection();
        vc.setId(1L);
        vc.setName("Test VC éë");
        Creator c = new Creator("Test", " Person");
        c.setOrganisation("Test Org");
        vc.getCreators().add(c);
        vc.setCreationDate(new Date());

        DoiRequest request = DoiRequestBuilder.createAutoGeneratedDoiRequest(prefix, vc, permaLinkService);
        String json = request.toJsonString();

        logger.info("Json={}", json);

        StringEntity jsonEntity = new StringEntity(json, StandardCharsets.UTF_8);
        logger.info("entity content type={}", jsonEntity.getContentType());
*/

    }
}
