version: '2'
services:
    webapp  :
        #image: registry.gitlab.com/clarin-eric/docker-tomcat8-dev:1.0.0
        image: docker-tomcat8:2.0.0-alpha1-1-g859185a
        ports:
            - 8081:8080
            - 8444:8443
            - 8001:8000
        volumes:
            - ./target:/webapps/
        networks:
            - vcr
      
    database:
        image: mysql:5.7.18
        environment:
            MYSQL_ROOT_PASSWORD: vcr-root
            MYSQL_DATABASE: vcr
            MYSQL_USER: vcruser
            MYSQL_PASSWORD: vcrpassword
        ports:
            - 3306:3306
        networks:
            - vcr
        volumes:
            - /Users/wilelb/mysql-vcr-data:/docker-entrypoint-initdb.d 
    
networks:
  vcr:
    external: false
            


