version: '2'
services:
    webapp  :
        image: registry.gitlab.com/clarin-eric/docker-alpine-supervisor-java-tomcat-base:1.3.5
        environment:
            - "CATALINA_OPTS=-Djava.security.egd=file:/dev/urandom"
        ports:
            - 8081:8080
            - 8444:8443
            - 8001:8000
        volumes:
            - ./webapps:/srv/tomcat8/webapps
            - ./conf/server.jks:/cert/server.jks
            - ./conf/vcr-admin.conf:/root/vcr-admin.conf
            - ./conf/fluentd/vcr.conf:/etc/fluentd/conf.d/vcr.conf
            - ./conf/tomcat-users.xml:/srv/tomcat8/conf/tomcat-users.xml
        networks:
            - vcr
      
    database:
        image: "mariadb:10.3.10-bionic"
        environment:
            MYSQL_ROOT_PASSWORD: vcr-root
            MYSQL_DATABASE: vcr
            MYSQL_USER: vcruser
            MYSQL_PASSWORD: vcrpassword
        ports:
            - 3306:3306
        networks:
            - vcr
        volumes:
            - /Users/wilelb/mysql-vcr-data:/docker-entrypoint-initdb.d 
    
networks:
  vcr:
    external: false
            


