package eu.clarin.cmdi.virtualcollectionregistry.pid;

import eu.clarin.cmdi.virtualcollectionregistry.gui.Application;
import eu.clarin.cmdi.virtualcollectionregistry.model.Creator;
import eu.clarin.cmdi.virtualcollectionregistry.model.VirtualCollection;

public class DoiRequestBuilder {

    public static DoiRequest createGenerateDoiRequest(String prefix, String postfix, VirtualCollection vc) {
        DoiRequest request = createBasicDoiRequest(vc);
        request.setDoi(prefix+"/"+postfix);
        return request;
    }

    public static DoiRequest createAutoGeneratedDoiRequest(String prefix, VirtualCollection vc) {
        DoiRequest request = createBasicDoiRequest(vc);
        request.setPrefix(prefix);
        return request;
    }

    private static DoiRequest createBasicDoiRequest(VirtualCollection vc) {
        DoiRequest request = new DoiRequest();
        final String url = Application.get().getPermaLinkService().getCollectionUrl(vc);
        request.setUrl(url);
        request.setPublicationYear(vc.getYear());
        request.addTitle(vc.getTitle());
        for(Creator vc_creator: vc.getCreators()) {
            if(vc_creator.getOrganisation() != null && !vc_creator.getOrganisation().isEmpty()) {
                request.addCreator(vc_creator.getFamilyName(), vc_creator.getGivenName(), vc_creator.getOrganisation());
            } else {
                request.addCreator(vc_creator.getFamilyName(), vc_creator.getGivenName());
            }
        }
        return request;
    }
}
