package eu.clarin.cmdi.virtualcollectionregistry.pid;

import eu.clarin.cmdi.virtualcollectionregistry.PermaLinkService;
import eu.clarin.cmdi.virtualcollectionregistry.gui.Application;
import eu.clarin.cmdi.virtualcollectionregistry.model.Creator;
import eu.clarin.cmdi.virtualcollectionregistry.model.VirtualCollection;

import java.net.URI;

public class DoiRequestBuilder {

    public static DoiRequest createGenerateDoiRequest(String prefix, String postfix, VirtualCollection vc, PermaLinkService permaLinkService) {
        DoiRequest request = createBasicDoiRequest(vc, permaLinkService);
        request.setDoi(prefix+"/"+postfix);
        return request;
    }

    public static DoiRequest createAutoGeneratedDoiRequest(String prefix, VirtualCollection vc, PermaLinkService permaLinkService) {
        DoiRequest request = createBasicDoiRequest(vc, permaLinkService);
        request.setPrefix(prefix);
        return request;
    }

    public static DoiRequest createUpdateDoiUrlRequest(String prefix, String postfix,  URI target) {
        DoiRequest request = new DoiRequest();
        request.setUrl(target.toString());
        return request;
    }


    private static DoiRequest createBasicDoiRequest(VirtualCollection vc, PermaLinkService permaLinkService) {
        DoiRequest request = new DoiRequest();
        final String url = permaLinkService.getCollectionUrl(vc);
        request.setUrl(url);
        request.setPublicationYear(vc.getYear());
        request.addTitle(vc.getTitle());
        for(Creator vc_creator: vc.getCreators()) {
            if(vc_creator.getOrganisation() != null && !vc_creator.getOrganisation().isEmpty()) {
                request.addCreator(vc_creator.getFamilyName(), vc_creator.getGivenName(), vc_creator.getOrganisation());
            } else {
                request.addCreator(vc_creator.getFamilyName(), vc_creator.getGivenName());
            }
        }
        return request;
    }
}
