openapi: 3.0.1
info:
  title: Virtual Collection Registry REST API
  description: The Virtual Collection Registry (VCR) REST API is documented following
    the open API specification. The UI on this page.allows you to test and play with
    the various resources.<br />Description of the API protocol is available <a href="../Protocol.txt">here</a>.<br
    /><br />In addition to the REST API there are submission endpoints available to
    provide a low friction integration with external data catalogues. Documentation
    is available <a href="https://github.com/clarin-eric/VirtualCollectionRegistry/blob/master/doc/Integration.md">here</a>.<br
    />Submission endpoint test paages:<ul><li><a target="_new" href="../test_vc_submission_extensional.html">Extensional
    collections</a></li><li><a target="_new" href="../test_vc_submission_intensional.html">Intensional
    collections</a></li></ul><br />Code repository is hosted on <a href="https://github.com/clarin-eric/VirtualCollectionRegistry">GitHub</a>.
  version: 1.0.0
servers:
- url: http://localhost:8080/vcr/service
  description: Local API endpoint
  variables: {}
paths:
  /:
    get:
      operationId: getDescription
      responses:
        default:
          description: default response
          content:
            text/xml: {}
  /my-virtualcollections:
    get:
      summary: Get the list of private collections
      description: Get the list of private collections for the user identified via
        the supplied API key.
      operationId: getMyVirtualCollections
      parameters:
      - name: q
        in: query
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      - name: count
        in: query
        schema:
          type: integer
          format: int32
          default: -1
      responses:
        "401":
          description: Missing or invalid API key in Authorization header.
          content:
            text/plain: {}
        "404":
          description: Missing description.
          content:
            text/plain: {}
        "500":
          description: Unexpected server side error.
          content:
            text/html: {}
        "200":
          description: JVM system properties of a particular host.
          content:
            application/json: {}
            application/xml: {}
      security:
      - apiKey: []
  /v1/collections:
    get:
      operationId: getVirtualCollections
      parameters:
      - name: q
        in: query
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      - name: count
        in: query
        schema:
          type: integer
          format: int32
          default: -1
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
    post:
      operationId: createVirtualCollection
      requestBody:
        content:
          text/xml:
            schema:
              type: object
          application/xml:
            schema:
              type: object
          application/json:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
  /v1/collections/{id}:
    get:
      operationId: getVirtualCollectionDetailsRedirect
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: default response
          content:
            text/html: {}
    put:
      operationId: updateVirtualCollection
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/xml:
            schema:
              type: object
          application/xml:
            schema:
              type: object
          application/json:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
    delete:
      operationId: deleteVirtualCollection
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
  /v1/collections/{id}/state:
    get:
      operationId: getVirtualCollectionState
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
    post:
      operationId: setVirtualCollectionState
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/xml:
            schema:
              type: string
              xml:
                name: State
              enum:
              - private
              - public
              - public_frozen
          application/xml:
            schema:
              type: string
              xml:
                name: State
              enum:
              - private
              - public
              - public_frozen
          application/json:
            schema:
              type: string
              xml:
                name: State
              enum:
              - private
              - public
              - public_frozen
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
  /v2/collections:
    get:
      operationId: getVirtualCollections_1
      parameters:
      - name: q
        in: query
        schema:
          type: string
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
          default: 0
      - name: count
        in: query
        schema:
          type: integer
          format: int32
          default: -1
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
    post:
      operationId: createVirtualCollection_1
      requestBody:
        content:
          text/xml:
            schema:
              type: object
          application/xml:
            schema:
              type: object
          application/json:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
  /v2/collections/{id}:
    get:
      operationId: getVirtualCollectionDetailsRedirect_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: default response
          content:
            text/html: {}
    put:
      operationId: updateVirtualCollection_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/xml:
            schema:
              type: object
          application/xml:
            schema:
              type: object
          application/json:
            schema:
              type: object
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
    delete:
      operationId: deleteVirtualCollection_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
  /v2/collections/{id}/state:
    get:
      operationId: getVirtualCollectionState_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
    post:
      operationId: setVirtualCollectionState_1
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/xml:
            schema:
              type: string
              xml:
                name: State
              enum:
              - private
              - public
              - public_frozen
          application/xml:
            schema:
              type: string
              xml:
                name: State
              enum:
              - private
              - public
              - public_frozen
          application/json:
            schema:
              type: string
              xml:
                name: State
              enum:
              - private
              - public
              - public_frozen
      responses:
        default:
          description: default response
          content:
            text/xml: {}
            application/xml: {}
            application/json: {}
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: Authorization
      in: header
