version: '3'
services:
  webapp  :
    image: registry.gitlab.com/clarin-eric/docker-alpine-supervisor-java-tomcat-base:9.0.70-java17_1.0.0
    environment:
      - "CATALINA_OPTS=-Djava.security.egd=file:/dev/urandom -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
    ports:
      - 8080:8080 #http port
      - 8000:8000 #JDPA debugging port
    volumes:
      - ../..:/app/src
      - ./conf/tomcat/init.sh:/init/init-tomcat.sh
      - ./conf/vcr/vcr-admin.conf:/conf/vcr-admin.conf
      - ./conf/vcr/pidproviders.properties:/conf/pidproviders.properties
      - ./conf/tomcat/vcr-context.xml:/srv/tomcat/conf/Catalina/localhost/ROOT.xml
      - ./conf/tomcat/tomcat-users.xml:/srv/tomcat/conf/tomcat-users.xml
      - ./conf/fluentd/vcr.conf:/etc/fluentd/conf.d/vcr.conf
      - ./conf/usr/bin/tomcatFindSkipJars.bash:/usr/bin/tomcatFindSkipJars
#      - ./conf/server.jks:/cert/server.jks
    networks:
      - vcr

  database:
    image: "mariadb:10.3.10-bionic"
    environment:
      MYSQL_ROOT_PASSWORD: vcr-root
      MYSQL_DATABASE: vcr
      MYSQL_USER: vcruser
      MYSQL_PASSWORD: vcrpassword
    networks:
      - vcr
    volumes:
      - maria_db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  maria_db_data:
    external: false

networks:
  vcr:
    external: false
