version: '2'
services:

  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.10
    ports:
      - "9080:8080"
    depends_on:
      - "databasepg"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://vcruser:vcrpassword@databasepg:5432/vcr
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## Enable authentication
      HASURA_GRAPHQL_ADMIN_SECRET: "adminsecret1234"
      HASURA_GRAPHQL_AUTH_HOOK: "https://auth/authenticate"
      HASURA_GRAPHQL_AUTH_HOOK_MODE: "GET"
    volumes:
      - ./ca/myCA.pem:/etc/ssl/certs/myCA.pem #https://github.com/hasura/graphql-engine/issues/2553#issuecomment-531171075
    networks:
      - vcr

  auth:
    image: "docker-auth-webhook:fb9bd32"
    command: --hostname "0.0.0.0"
    restart: always
    volumes:
      - ./cert:/tls:ro
    networks:
      - vcr

#curl --header "Content-Type: application/json" \
#  --request POST \
#  --data '{"query": "query MyQuery {vcr_virtualcollection {id}}"}' \
#  http://localhost:9080/v1/graphql